### ISSUE TITLE
Using Html.br truncates output

### ISSUE THREAD

**Issue by hansallis** [MartinSStewart/send-grid#11]
Hi, thanks for providing this module. I've noticed a regression issue going from 4.1.0 to 4.1.1. It seems that using `Html.br` truncates the output of the html:
`Email.Html.div [] [Email.Html.text "line 1", Email.Html.br [] [], Email.Html.text "line 2"]`
This erroneously results in:
`<div>line 1<br></div>`

I'll send in a pull request to demonstrate using an elm-test as well. It obviously has something to do with the list of void elements.

**Comment by MartinSStewart** [comment]
Thanks for the issue and PR. I've published a fix now https://package.elm-lang.org/packages/MartinSStewart/send-grid/4.1.2/
